-- ============================================================================
-- MENU ITEMS DATA
-- Generated from menu-items.ts
-- Run this AFTER 003_menu_items_table.sql
-- ============================================================================

-- Clear existing menu items for this tenant
DELETE FROM menu_items WHERE tenant_id = '63c69ee3-0167-4799-8986-09df2824ab93';

-- Insert all menu items
INSERT INTO menu_items (tenant_id, name, category, description, display_order) VALUES
('63c69ee3-0167-4799-8986-09df2824ab93', 'Shrimp and Crab Bisque', 'Appetizers', 'A mixture of shrimp, crab, onions, carrots, celery, house oil , thyme, garlic, bay leaves, sherry, butter, flour, shrimp poaching liquid , clam juice, lobster base , heavy cream, tomato paste, Old Bay s easoning , salt and pepper. Garnished with corn, red peppers  and chives.  We offer both a bowl and a cup of soup.', 0),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Baked French Onion Soup', 'Appetizers', 'Caramelized onions and butter simmered with white wine, chicken stock , sugar, house oil , salt, and pepper.  Topped with garlic crouton  and covered with Swiss and Asiago cheese s.  We offer both a bowl and a cup of soup.', 1),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Mediterranean Chicken Skewers', 'Appetizers', 'Two skewers of chicken breast pieces (5 pieces each on each; equaling about 10 oz. total), marinated in Mediterranean marinade .  Served with a drizzle of yogurt sauce , chicken jus  and a ramekin of yogurt sauce .', 2),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Bison Meatballs', 'Appetizers', 'Six bison meatballs heated up in garlic butter, then tossed with chicken jus, tomato jam and tomato basil sauce. Garnished with Asiago cheese and parsley. Served on top of a garlic crouton.', 3),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Baked Goat Cheese', 'Appetizers', 'Two 2 oz . balls of domestic goat cheese (Wisconsin) with tomato basil sauce , topped with Japanese breadcrumbs and parsley.  Baked in the oven.  Served with flatbread ( flatbread  brushed with garlic puree , sprinkled with Asiago cheese  and parsley) and baked in the oven.', 4),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Crispy Fried Calamari', 'Appetizers', '10 oz. calamari (squid) marinated in buttermilk then coated with seasoned flour  and deep fried.  Served on top of a garlic crouton  with a ramekin of ranch dressing  and a ramekin of cocktail sauce .  Garnished with a lemon wedge.', 5),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Shrimp Cocktail', 'Appetizers', 'Five 13 -15 count Gulf shrimp, poached in shrimp poaching liquid , then peeled and chilled.  Served with side of cocktail sauce  with a dollop of horseradish .  Garnished with lemon wedges.', 6),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Oven Roasted Lump Crab Cakes', 'Appetizers', 'Two 3 oz. crab cakes roasted to a golden brown in the oven.  The crab cake consists  of a mixture of saltin e crackers , super lump crab meat, Old Bay seasoning , parsley, mayonnaise , egg, Dijon musta rd, lemon j uice, Worcestershire sauce  and salt .  Served with a ramekin of mustard mayonnaise.   Garnished with a lemon wedge.', 7),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Applewood Smoked Bacon Wrapped Sea Scallops Skewers', 'Appetizers', 'Two skewers  of 3 scallops each equaling about 7 or 8 oz., wrapped in bacon  and skewered.  Roasted in the oven with cooking spray .  Served with apricot dipping sauce .  Garnished with a lemon wedge and chives.', 8),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Field Salad', 'Salads', 'Field greens , sliced cucumbers, tomato wedges  and shredded carrots served with choice of dressing on side. Dressing choices: citrus lime vinaigrette , ranch , balsamic vinaigrette , red wine vinaigrett e, blue cheese dressing, lemon P armesan vinaigrette , lemon herb vinaigrette , or Caesar .', 9),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Caesar Salad', 'Salads', 'Romaine lettuce tossed with croutons , Parmesan cheese and Caesar dressing (anchovy, garlic, lemon juice, Dijon mustard , Asiago cheese, pasteurized egg yolk, red wine vinegar, house oil , salt, pepper).  OFFER FRESH GROUND PEPPER.', 10),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Add roasted wild mushrooms  or Applewood smoked bacon  to any burger for $2.00 each Thick Prime Angus Burger /Cheeseburger', 'Sandwiches: Prime Burgers', '8 oz.  ground beef  seasoned with salt and pepper, then grilled to desired temperature.   Served on a buttered and toasted sesame seed bun  with lettuce and tomato.  Served with French fries, coleslaw  and a ramekin of ketchup. Choice of American, yellow cheddar, jalapeno jack, Swiss , blue cheese  crumbles  or white cheddar  for cheeseburger.', 11),
('63c69ee3-0167-4799-8986-09df2824ab93', 'All Natural Turkey Burger', 'Sandwiches: Prime Burgers', '5.33 oz. all natural ground turkey burger  seasoned with char-crust  and grilled.  Topped with white cheddar cheese and roasted onions .  Served on a buttered and toasted sesame seed bun  with yellow mustard  on the bottom of the bun, mayonnaise  on the top of the bun with lettuce and tomato.  Served with French fries, coleslaw  and a ramekin of ketchup.', 12),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Crispy Hot Honey Chicken Sandwich', 'Sandwiches: Signatures', '5-6 oz. chicken breast in fried chicken batter  and fried chicken flour , then fried.  Tossed in hot honey sauce .  Serv ed on a buttered and toasted sesame seed bun  with jalapeno jack cheese melted on bottom bun, lettuce, Bubbies  bread and butter pickles  with spicy mayo  on top half of bun.  Served with French fries, coleslaw and a ramekin of ketchup.', 13),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Grilled Chicken Club', 'Sandwiches: Signatures', '5 oz. chicken breast brined  and marinated with mustard mayonnaise .  Then grilled and topped with avocado , bacon , jalapeno jack c heese  and mustard mayonnaise .  Served on a buttered and toasted sesame seed bun  with lettuce and tomato.  Served with French fries, coleslaw  and a ramekin of ketchup.', 14),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Roasted Prime Rib French Dip', 'Sandwiches: Signatures', '6 oz. sliced Prime Rib (medium rare to medium) served on buttered and toasted buttery onion bun.  Served with a soup cup of au jus , horseradish cream sauce , coleslaw, French fries and a ramekin of ketchup.', 15),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Blackened New York Strip Steak Sandwich', 'Sandwiches: Signatures', '6 oz. New York s trip pounded and brushed with melted butter and seasoned with blackening spice  then grilled medium rare to medium.  Served on butter ed and toasted buttery onion bun  with white cheddar cheese, arugula, ancho mayo  and tomatoes.  Served with French fries, coleslaw  and a ramekin of ketchup.', 16),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Sliced Turkey Sandwich', 'Sandwiches: Signatures', '4 oz. of sliced turkey served on buttered and toasted multi -grain  bread  with honey Dijon mustard , arugul a, tomatoes, cucumbers, avocado  and white cheddar  cheese .  Served with French fries, coleslaw and a ramekin of ketchup.', 17),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Basil Hayden''s Bourbon Marinated Tenderloin Tips', 'Filets', 'Tenderloin tips in a bourbon marinade .  Broiled to desired temperature.  Brushed with steak butter .  Two 4 oz. tips at lunch, three 4 oz. tips at dinner.  Served with au jus  and roasted onions .  Served with choice of side.', 18),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Petite Filet Mignon/Filet Mignon', 'Filets', 'Filet mignon brushed with melted butter and seasoned with salt and pepper, then broiled to desired temperature. Topped with steak butter  and served on a garlic crouton  with au jus . The lunch and dinner petite filets are 7 oz. The dinner filet is 10 oz.  Served with choice of side.', 19),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Horseradish Crusted Filet', 'Filets', 'Filet mignon brushed with melted butter and seasoned with salt and pepper.  Wrapped in bacon, broiled and topped with a horseradish crust .  Served on a garlic crouton  with au jus  and a side of horseradish cream sauce .  The dinner portion is a 10 oz. portion.  Served with choice of side.  Garnished with parsley.  A lunch portion is available with a 7 oz. filet.', 20),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Filet Medallion Duo/Filet Medallion Trio', 'Filets', '3 oz. f ilet medallions brushed with melted butter and seasoned with salt and pepper.  Broiled to desired temperature and topped with the guest choice of crust s (two or t hree choices).  Crust choices are Horseradish , Blue Cheese , Parmesan , Mushroom , Garlic  (GF) or Peppercorn  (GF).  Duo = two filets.  Trio = three filets.  Served with au jus . Served with choice of side.', 21),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Mushroom Crusted Fancy Pork Chops', 'Steaks and Chops', 'All natural boneless pork rib chops brined for 8 hours (sugar, salt, water, fresh oranges, garlic, rosemary, thyme, black peppercorns, crushed red chilies).  Broiled to medium and topped with mushroom crust  and browned under broiler.  The lunch portion is one 8 oz. chop.  The dinner portion is two 8 oz. chops.  Served with au jus  and a choice of side.', 22),
('63c69ee3-0167-4799-8986-09df2824ab93', 'New York Strip Steak', 'Steaks and Chops', '14 oz. New York strip brushed with melted butter and seasoned with salt and pepper, then broiled to desired temperature. Topped with steak butter and au jus. Served with choice of side.', 23),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Roumanian Skirt Steak', 'Steaks and Chops', '12 oz. c enter cut skirt steak marinated in steak marinade , then grilled to desired temperature.  Brushed with steak butter  and served with au jus.   Garnished with roasted red onions .  Served with choice of side.  L unch portion is available upon request with a 6 oz. pi ece.', 24),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Porterhouse', 'Steaks and Chops', 'The “King” of steaks.  22 oz. porterhouse is two steaks i n one.  One side is a New York strip and the other is a filet mignon.  The steak is brushed with melted butter, seasoned with salt, p epper  and char-crust,  then broiled to desired temperature.  Topped with steak butter  and au jus.   Served with choice of side.', 25),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Char -Crust  Bone -In Rib Eye', 'Steaks and Chops', '20 oz. beef “prime rib” chop brushed with melted butter and seasoned with salt and pepper and char-crust. Broiled to desired temperature .  Topped with steak butter  and au jus .  Served with choice of side.', 26),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Broiled Lamb Porterhouse Chops', 'Steaks and Chops', 'Three 6 oz. Colorado lamb porterhouse chops (part filet and part New York with bone) brushed with melted butter and se asoned with salt and pepper and char–crust. Broiled to order.  Topped with steak butter  and au jus .  Served with mint chimichurri  on the side .  Served with choice of side.', 27),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Oscar Style – Added onto any steak', 'Steaks and Chops', 'Steak is topped with 2 oz. crab meat warmed with a little butter, béarnaise sauce  and 4 oz. blanched asparagus (butter, salt, pepper).', 28),
('63c69ee3-0167-4799-8986-09df2824ab93', 'ROASTED PRIME RIB', 'Steaks and Chops', '“King of Roasts” is rubbed with fresh garlic, sea salt, cracked black pepper and slow roasted for six hours and served with horseradish sauce To provide our guests with the best cut of prime rib possible; all of our prime rib is roasted to medium rare to medium.  Rar e is not available (suggest a rib -eye).  If the guest would like well done, we recommend an end cut. Roasted Prime Rib of Beef  10 OZ PRIME/16 OZ PRIME/22 OZ PRIME', 29),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Roasted Prime Rib of Beef', 'Prime Rib', 'The prime ribs are rubbed with house oil , fresh minced garlic, kosher salt, and black pepper.  It is then seared in the oven and slow roasted.  Served with horseradish cream sauce  and au jus.   At lunch the guest has a choice of an 8 oz. (Lunch Cut) or 10 oz. (Regular Cut).  At dinner the guest has a choice of a 10 oz. (Regular Cut), 16 oz. (Queen Cut), or 22 oz. (King Cut) portion.  All served with a choice of side.', 30),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Coconut Shrimp', 'Fresh Fish and Seafood', '16-20 count shrimp are butterflied and then dipped in seasoned flour , lightly beaten eggs whites, and coconut crumbs ( garlic butter , parsley, Japanese bread crumbs , shredded coconut).  Seared on a skillet in the oven.  Served with a ramekin of coconut dipping sauce (reduced coconut milk, dark brown sugar, rice wine vinegar, San J Tamari , ginger, chili paste), which is garnished with fresh chives.  Served with a lemon wedge.  Dinner - 8 shrimp; Lunch - 6 shrimp; Add to entrée - 3 shrimp.  Lu', 31),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Cedar Planked Salmon', 'Fresh Fish and Seafood', 'Farm raised Atlantic salmon from Canada .  Brushed with BBQ chicken spice .  Baked in the oven on a cedar plank. Glazed with brown sugar, San J Tamari , Dijon  mustard  and butter.  At lunch it is a 6 oz. portion.  At dinner it is an 8 oz. portion.  Served with a choice of side.', 32),
('63c69ee3-0167-4799-8986-09df2824ab93', 'East Coast Scallops De Jonghe', 'Fresh Fish and Seafood', '8 scallops equaling 8 oz. (20 count) are placed in a pasta boat with clam juice and topped with the DeJonghe crust . Baked in the oven. S erved with parsley, lemon wedge  and choice of side.', 33),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Lump Crab Cakes', 'Fresh Fish and Seafood', '6 oz. crab cake  roasted to a golden brown in the oven.  Lunch portion is one crab cake and dinner portion is two crab cakes.  Served with a ramekin of mustard mayonnaise and a lemon wedge .  Garnished with chives.  Served with choice of side.', 34),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Wildfire’s Macadamia Nut Crusted Halibut', 'Fresh Fish and Seafood', 'Fresh Alaskan h alibut dipped in egg whites, seasoned flour , salt  and pepper.  Crusted with macadamia nuts, garlic butter, salt, pepper, parsley, and Japanese breadcrumbs .  Roasted in the oven with asparagus and served with lemon butter sauce .  Lunch portion is 5 oz.  Dinner portion is 7 oz. Served with choice of side.', 35),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Parmesan Crusted Cod', 'Fresh Fish and Seafood', 'Fresh c od dipped in egg whites, seasoned flour , salt  and pepper.  Crusted with garlic breadcrumbs  and P armesan cheese.  Roasted in the oven with green beans and served with lemon b utter sauce  and dollops of tomato jam . Served with choice of side.  Lunch portion is 5 oz.  Dinner portion is 7 oz.', 36),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Cornbread Crusted Cod', 'Fresh Fish and Seafood', 'Fresh c od dipped in egg whites, seasoned flour , salt and pepper. Crusted with garlic breadcrumbs  and cornbread crumbs .  Roasted in the oven.  Served with blanched shaved Brussel s sprouts tossed in garlic butter , salt and pepper.  Served with cranberry lemon butter  (cranberry sauce , lemon butter sauce ).  Served with choice of side. Lunch portion is 5 oz.  Dinner portion is 7 oz.', 37),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Spit Roasted Half Chicken', 'Chicken and Barbecue', '½ of a 3¾ pound chicken, marinated in the herb chicken marinade  (cayenne pepper, oregano, thyme, tarragon, curry powder , rosemary, garlic, salt, pepper, bay leaves, olive oil, dried onions, chicken stock , butter, Dijon  mustard ).  Spit roasted and served with chicken juice.   Served with choice of side.', 38),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Barbecued Chicken', 'Chicken and Barbecue', '½ of a 3¾ pound chicken, marinated in the herb chicken marinade , spit roasted, rubbed with BBQ chicken spice  and brushed with BBQ sauce .  Served with BBQ sauce  and choice of side.', 39),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Lemon Pepper Chicken Breasts', 'Chicken and Barbecue', 'Skin on, boneless chicken breast marinated in fresh lemon juice, melted butter, Lawry''s seasoning  and cracked black pepper.  Roasted in the oven.  Lunch portion is one 8 oz. breast, and the dinner portion is two 8 oz. breasts.  Served with a squeeze of fresh lemon, grilled lemon slice and chicken juice .  Served with a choice of side.', 40),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Monday & Tuesday: Southern Fried Chicken', 'Nightly Specials', 'Four pieces of chicken (breast, thigh, wing, and leg) dipped in fried chicken batter  and fried chicken seasoned flour and then deep fried.  Served with mashed potatoes , mushroom gravy , buttermilk biscuit , a ramekin of honey  and coleslaw.', 41),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Wednesday: Spit Roasted Half Long Island Duck', 'Nightly Specials', 'One half of a 5 pound duck.  The duck is stuffed with onions and thyme and seasoned with salt, pepper and thyme. Slow roasted for two hours on the spit.  Brush ed with balsamic vinegar, honey  and orange zest glaze.  Served in a cherry sauce (honey, shallots, orange juice and zest, thyme, balsamic vinegar, cherry juice, duck stock , Door County cherries, corns tarch, butter, pepper) and wild rice  (blend of long grain, brown rice, sweet brown rice, wehani, black japonica, and wild rice pieces ba', 42),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Thursday: Beer Braised Short Ribs', 'Nightly Specials', '12 oz. boneless beef short rib seasoned with house oil , salt, pepper and BBQ chicken spice .  Seared and then slowly braised for 3 hours with carrots, onions, celery, garlic, tomato paste, bay leaves, thyme, rosemary, IPA beer, tomatoes, chicken stock  and beef stock .  Served with reduced braising liquid (mixed with cornstarch and butter), roast ed root vegetables (turnips, parsnips, carrots, shallots, garlic, thyme, rosemary, salt, pepper, house oil ) and mashed potatoes.', 43),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Friday & Saturday: Filet Mignon Wellington', 'Nightly Specials', '7 oz. f ilet brushed with melted butter and seasoned with salt and pepper, then seared.  Wrapped in puff pastry  with a mushroom crust .  Baked medium rare to medium and s erved with shallot  balsamic sauce , broccolini tossed with garlic butter  and A siago breadcrumbs ( Japanese breadcrumbs , garlic butter , Asiago cheese) and au gratin potatoes .', 44),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Sunday: Spit Roasted Turkey Dinner', 'Nightly Specials', 'Whole turkey breast brined  in water, salt  and sugar, then marinated in fresh herb marinade  and spit roasted.  Sliced into an 8 oz. portion.  Served with stuffing ( sourdough bread , butter, onions, celery, mushrooms, cayenne pepper, carrots, garlic, rosemary, sage, thyme, basil, salt, pepper, chicken base , chicken stock , eggs, cooking spray ), mashed potatoes , mushroom gravy  and a ramekin of cranberry sauce (cranberries, water, sugar, salt, Grand Marnier, Cognac).', 45),
('63c69ee3-0167-4799-8986-09df2824ab93', 'French Fries', 'Sides', 'Idaho russet potatoes hand cut with skins on, soaked in cold water and apple cider vinegar overnight, then blanched quickly in the fryer. Cooled and fried a second time for serving. Tossed with salt and pepper and served with a ramekin of ketchup.', 46),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Red Skin Mashed Potatoes', 'Sides', 'Red skin potatoes and Idaho russet potatoes (with skin) mashed with butter, half and half , whipping cream , salt  and pepper.', 47),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Steamed Broccoli with Lemon Vinaigrette', 'Sides', '5 oz. of steamed broccoli crowns served with lemon herb vinaigrette .', 48),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Creamed Spinach', 'Sides', 'Mixture made from spinach, cre am, butter, flour, nutmeg, salt  and pepper.', 49),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Au Gratin Potatoes', 'Sides', 'Thinly sliced potatoes layered with cr eam, white cheddar cheese, salt  and pepper.  Baked slowly in oven.', 50),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Idaho Baked Potato', 'Sides', '40 count Idaho potato with rubbed with house oil , salt and pepper, baked  and spilt open.  Available with sour cream or butter or both on the side.  $1.95 additional with entrees  and sandwiches.', 51),
('63c69ee3-0167-4799-8986-09df2824ab93', 'BBQ Rubbed Sweet Potato', 'Sides', '40 count sweet potato rubbed with BBQ chicken spice  and house oil , baked  and spit open.  Available with butter or brown sugar or both on the side.  $1.95 additional with entrees  and sandwiches.', 52),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Mac and Cheese', 'Sides', 'Elbow macaroni  mixed with whipping cream , whole milk, Land o’Lakes Golden Velvet Yellow Cheese Spread . Topped with cheddar cheese slices and baked.  $1.95 additional with entrees  and sandwiches.', 53),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Roasted Mushroom Caps', 'Sides', 'Mushroom caps roasted with garlic, shallots, white wine, fresh thyme, chicken stock  and butter.  $3 .95 additional with entrees and sandwiches.', 54),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Roasted Market Vegetables', 'Sides', 'A blend of red onion, red pepper, Brussels sprouts, cauliflower and butternut squash roasted with house oil, salt and pepper.', 55),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Applesauce', 'Sides', 'Apples mixed w ith corn syrup, cinnamon, sugar  and fresh lemon juice.', 56),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Homemade Coleslaw', 'Sides', 'Cabbage and carrot mixed with coleslaw d ressing .', 57),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Triple  Layer Chocolate Cake', 'Desserts', 'Chocolate cake (eggs, canola oil, milk, vanilla extract, flour, sugar, baking powder, baking soda, salt, cocoa powder, water), and chocolate icing ( chocolate pistoles , egg yolks, sugar, heavy whipping cream). The pan is sprayed with cooking spray .  Outside of the cake is coated in toasted cake crumbs.  Topped with hot fudge  and whipped cream . Ala mode is an option.', 58),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Door County Cherry Pie', 'Desserts', 'Filling is a mixture of Door County cherries, sugar, c ornstarch, salt, almond extract  and Door County cherry juice. Placed in a pie crust shell  and topped with pie crust  topper .  Lightly brushed with a mix of egg and half and half  and sprinkled with sugar.  Served with whipped cream .', 59),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Key Lime Pie', 'Desserts', 'An individual pie made with a graham cracker crust  and real key lime filling (key lime juice, egg yolks, sweetened condensed milk, sugar, lemon juice).  Topped with whipped cream  and zest of lime.', 60),
('63c69ee3-0167-4799-8986-09df2824ab93', 'JD’s Cheesecake', 'Desserts', '2 layer cheese cake with graham cracker  crust  bottom only crust ( graham crackers , butter, sugar), cream cheese filling (cream cheese, sugar, eggs, salt, vanilla), baked and chilled.  Topped with a sour cream topping (sour cream, sugar, vanilla) and baked briefly.  Served cold with a cherry sauce (Door County cherries, orange and cherry juice, sugar, cinnamon sticks, almond extract, cornstarch and water)', 61),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Warm Chocolate Chip Cookie  Skillet', 'Desserts', 'A chocolate chip cookie (butter, sugar, brown sugar, vanilla, eggs, flour, salt, baking powder, chocolate chips ) served warm with a scoop of vanilla ice cream,  topped with whipped cream  and hot fudge .', 62),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Seasonal Berries Crisp', 'Desserts', 'A mixture of raspberr ies, strawberries, blackberries  mixed with warm berry sauce  and topped with crumbles of oatmeal raisin cookies (butter, sugar, brown sugar, eggs, vanilla, Domata’s gluten free flour , baking soda, baking powder, salt, Bob’s Red Mill gluten free rolled oats, raisins).  Garnished with vanilla ice cream.', 63),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Flourless Chocolate Cake/Birthday Dessert', 'Desserts', 'A slice of flourless chocolate cake ( chocolate  pistoles , butter, eggs, sugar, vanilla, salt, cocoa powder) served with whipped cream  and hot fudge .  Pan sprayed with cooking spray .', 64),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Grilled Cheese and Fries', 'Kids Menu', 'Two slices of multi -grain  bread  buttered on the outside.  Filled with thr ee slices of American cheese and b aked in the oven on a sizzle platter until golden brown.  Served with French fires, applesauce  and a ramekin of ketchup.', 65),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Chicken Fingers  and Fries', 'Kids Menu', '3 Kid ’s chicken f ingers  deep fried  and served French fries,  applesauce  and a ramekin of ketchup.', 66),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Burger/Cheeseburger  and Fries', 'Kids Menu', '4 oz. ground beef grilled to well done.  Cheeseburger is  topped with American cheese and s erved with French fries, applesauce  and a ramekin of ketchup.', 67),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Macaroni and Cheese', 'Kids Menu', 'Elbow macaroni  mixed with whipping cream , whole milk, Land o’Lakes Velvet Yellow Cheese Spread .  Then topped with cheddar cheese slices and baked.  Served with applesauce .', 68),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Available upon request: Kids Filet & Mashed Potato', 'Kids Menu', 'Two 3 oz. f ilet medallions b rushed with melted butter, salt  and pepper.  Broiled to desired temperature and brushed with steak butter .  Served with au jus , mashed potatoes and applesauce .', 69),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Fresh Mozzarella Flatbread', 'Special Party Items', '6 oz. homemade  flatbread  hand stretched.  Brushed with roasted garlic puree  and then topped with shredded fresh mozzarella, tomato jam  and fresh basil.', 70),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Pasta  and Roasted Vegetable Pasta', 'Special Party Items', '8 oz. of pasta with garlic butter  and roasted vegetables .  Tossed with a tomato basil sauce  and topped with Asiago and goat cheeses.  Baked in the oven and g arnished with basil.', 71),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Roasted Vegetable Vegan Plate', 'Special Party Items', 'One Portobello mushroom cap  marinated in balsamic vinaigrette , salt, pepper then grilled.  4 oz. of as paragus roasted and tossed with balsamic vinaigrette , salt  and pepper.  8 oz. of roasted market vegetables .  One half of a baked sweet potato .', 72),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Wildfire Eggs Benedict', 'Brunch', 'Two poached eggs on English muffins topped with Canadian bacon and hollandaise sauce. Served with red skin mashed potatoes or fresh-cut french fries.', 73),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Classic Three-Egg Omelet', 'Brunch', 'Three-egg omelet with choice of fillings: cheddar cheese, Swiss cheese, mushrooms, onions, peppers, tomatoes, spinach, bacon, ham, or sausage. Served with red skin mashed potatoes or fresh-cut french fries.', 74),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Build Your Own Omelet', 'Brunch', 'Three-egg omelet with your choice of fillings: cheddar cheese, Swiss cheese, mushrooms, onions, peppers, tomatoes, spinach, bacon, ham, or sausage. Served with red skin mashed potatoes or fresh-cut french fries.', 75),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Wildfire Buttermilk Pancakes', 'Brunch', 'Three fluffy buttermilk pancakes served with butter and maple syrup. Add chocolate chips for an additional charge.', 76),
('63c69ee3-0167-4799-8986-09df2824ab93', 'French Toast', 'Brunch', 'Thick-cut brioche bread dipped in egg batter and griddled until golden brown. Served with butter, maple syrup, and fresh berries.', 77),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Steak and Eggs', 'Brunch', '7 oz. petite filet mignon cooked to your preference, served with two eggs any style, red skin mashed potatoes or fresh-cut french fries, and toast.', 78),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Smoked Salmon Benedict', 'Brunch', 'Two poached eggs on English muffins topped with smoked salmon, capers, red onions, and hollandaise sauce. Served with red skin mashed potatoes or fresh-cut french fries.', 79),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Avocado Toast', 'Brunch', 'Sliced avocado on toasted artisan bread with cherry tomatoes, red onion, feta cheese, and a drizzle of olive oil. Served with a side of mixed greens.', 80),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Breakfast Burrito', 'Brunch', 'Scrambled eggs, cheddar cheese, bacon, and hash browns wrapped in a flour tortilla. Served with salsa and sour cream on the side.', 81),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Chicken and Waffles', 'Brunch', 'Crispy fried chicken breast served on a Belgian waffle with maple syrup and butter. Served with a side of red skin mashed potatoes.', 82),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Breakfast Sandwich', 'Brunch', 'Fried egg, cheddar cheese, and your choice of bacon, ham, or sausage on a toasted English muffin. Served with red skin mashed potatoes or fresh-cut french fries.', 83),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Belgian Waffle', 'Brunch', 'Crispy Belgian waffle served with butter, maple syrup, and fresh berries. Add chocolate chips or whipped cream for an additional charge.', 84),
('63c69ee3-0167-4799-8986-09df2824ab93', 'Classic Breakfast', 'Brunch', 'Three eggs cooked to guest desired style, choice of three slices of bacon or two turkey sausage patties, breakfast potatoes and onions, one slice of multi-grain bread toasted and buttered then cut in half, and a ramekin of preserves.', 85)

ON CONFLICT (tenant_id, name) DO UPDATE 
SET category = EXCLUDED.category,
    description = EXCLUDED.description,
    display_order = EXCLUDED.display_order,
    updated_at = NOW();

-- Verification
SELECT 'Menu items loaded:' as status, count(*) as count 
FROM menu_items 
WHERE tenant_id = '63c69ee3-0167-4799-8986-09df2824ab93';

-- Show categories
SELECT category, count(*) as items 
FROM menu_items 
WHERE tenant_id = '63c69ee3-0167-4799-8986-09df2824ab93'
GROUP BY category 
ORDER BY category;
